"""The database schema, defined once for both backends.

Day 1's schema lived in a hand-written `CREATE TABLE` string that only SQLite
understood. Hosting the app means Postgres, and maintaining two dialects of the
same DDL by hand is how the two silently drift apart.

So the schema moves into SQLAlchemy Core table definitions. One definition
emits correct DDL for both engines, the expression language builds queries that
are portable by construction, and Alembic can diff this metadata against a live
database to generate migrations.

This is Core, not the ORM: the app already has its own dataclasses in
`models.py` and does not need a second object-mapping layer. Core gives the
portability and the query builder without the identity map, lazy loading, and
session-lifecycle rules that come with the ORM.
"""

from __future__ import annotations

from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    func,
    Integer,
    LargeBinary,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

# An explicit naming convention means Alembic generates stable, predictable
# names for constraints and indexes. Without it, autogenerated migrations churn
# on unnamed constraints and dropping one later becomes guesswork.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


users = Table(
    "users",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("apple_sub", String(255), unique=True),
    # Uniqueness is on lower(email), declared as an Index below rather than as a
    # column constraint. Postgres and SQLite both compare strings
    # case-sensitively, so a plain unique accepts Alice@x.edu alongside
    # alice@x.edu and a login resolves to whichever row is found first.
    Column("email", String(320)),
    Column("display_name", String(255)),
    # Null for accounts that have never set one: the seeded local user, and
    # anyone who signs in through a provider. Its absence is what makes password
    # login impossible for those accounts rather than a special case in the
    # login path.
    Column("password_hash", String(255)),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

# Declared here so `create_all` and Alembic produce the same shape. Both engines
# support expression indexes, so one definition covers them.
Index("uq_users_email_lower", func.lower(users.c.email), unique=True)


# What the browser holds is a random token; what this table holds is its SHA-256.
# A leaked database backup therefore does not hand the reader working sessions,
# for the same reason password_hash is not a password. The token is high-entropy
# and random, so a plain hash is right here -- there is nothing to brute-force
# and no need for a slow KDF on every authenticated request.
sessions = Table(
    "sessions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("token_hash", String(64), nullable=False, unique=True),
    Column(
        "user_id",
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False),
    # Absolute expiry, checked on every request. Not a sliding window: a session
    # that renews itself on use never ends for an attacker who keeps using it.
    Column("expires_at", DateTime(timezone=True), nullable=False),
    # Set when the session is deliberately ended. Kept as a row rather than
    # deleted so "this token was revoked" and "this token never existed" stay
    # distinguishable in the logs.
    Column("revoked_at", DateTime(timezone=True)),
    Column("user_agent", String(255)),
)


# One row per user who has connected Canvas. The token is stored encrypted by
# `vault`, and this table never holds a readable one.
#
# A separate table rather than columns on `users` because the lifetimes differ:
# disconnecting Canvas deletes a row here and leaves the account untouched, and
# a table nobody joins to by default is one fewer way for a token to end up in
# a SELECT * somewhere it should not be.
canvas_credentials = Table(
    "canvas_credentials",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "user_id",
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    Column("api_url", Text, nullable=False),
    Column("encrypted_token", Text, nullable=False),
    # Denormalised from the ciphertext so a rotation script can find rows to
    # re-encrypt with an indexed query rather than parsing every value.
    Column("key_version", String(16), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    # Set after a successful sync, so the UI can say when it last worked without
    # implying the credentials are good just because they exist.
    Column("verified_at", DateTime(timezone=True)),
)


# Background work: indexing and Canvas sync, which are both too slow to hold a
# request open for. Rows are the queue and the audit trail at once.
jobs = Table(
    "jobs",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "user_id",
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("kind", String(32), nullable=False),
    Column("status", String(16), nullable=False, default="queued"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("finished_at", DateTime(timezone=True)),
    # A short human-readable summary on success, or the error on failure. Never
    # a traceback: this is returned to the user, and a traceback leaks paths and
    # sometimes credentials from the frame locals.
    Column("detail", Text, default=""),
    CheckConstraint(
        "status IN ('queued', 'running', 'succeeded', 'failed')", name="status"
    ),
)
# The queue read is "oldest queued job", and the status read is "this user's
# recent jobs". Both want this.
Index("ix_jobs_status_created", jobs.c.status, jobs.c.created_at)


courses = Table(
    "courses",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("canvas_id", String(64)),
    Column("name", Text, nullable=False),
    Column("course_code", String(64)),
    Column("synced_at", DateTime(timezone=True)),
    # Per-user uniqueness: two students can both be in Canvas course 101.
    UniqueConstraint("user_id", "canvas_id", name="uq_courses_user_canvas"),
)


assignments = Table(
    "assignments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("canvas_id", String(64)),
    Column(
        "course_id",
        Integer,
        ForeignKey("courses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, default=""),
    Column("due_at", String(64)),
    Column("points_possible", Float),
    Column("submission_types", String(255), default=""),
    Column("html_url", Text),
    Column("synced_at", DateTime(timezone=True)),
    UniqueConstraint("course_id", "canvas_id", name="uq_assignments_course_canvas"),
)


notes = Table(
    "notes",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("course_id", Integer, ForeignKey("courses.id", ondelete="SET NULL")),
    Column("title", Text, nullable=False),
    Column("body", Text, nullable=False),
    Column("source_type", String(32), nullable=False, default="note"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("source_type IN ('note', 'transcript')", name="source_type"),
)


chunks = Table(
    "chunks",
    metadata,
    Column("id", Integer, primary_key=True),
    # Denormalised from notes: retrieval filters this table on every query.
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "note_id",
        Integer,
        ForeignKey("notes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("ordinal", Integer, nullable=False),
    Column("text", Text, nullable=False),
    Column("chunk_size", Integer, nullable=False),
    Column("chunk_overlap", Integer, nullable=False),
)


# `vector` stays a byte blob here so this definition mirrors the day-1 schema
# exactly. Commit 5 adds the native pgvector column alongside it.
embeddings = Table(
    "embeddings",
    metadata,
    Column("owner_type", String(32), primary_key=True),
    Column("owner_id", Integer, primary_key=True),
    Column("model", String(128), primary_key=True),
    Column("dim", Integer, nullable=False),
    Column("vector", LargeBinary, nullable=False),
)
Index("ix_embeddings_type_model", embeddings.c.owner_type, embeddings.c.model)


def add_native_vector_column(dim: int) -> None:
    """Attach the `embedding` column to the metadata so queries can name it.

    Called at connect time when the dialect is Postgres. It is not in the Table
    definition above because the dimension is not known until then -- it comes
    from EMBEDDING_DIM, and pgvector needs a concrete number to build an index.

    `metadata` is module-global, so a process that connects to Postgres and then
    to SQLite carries this column into the SQLite DDL as well. That does not
    happen in the app, which talks to one backend, but it does in a test run that
    covers both. Hence the variant: on SQLite the column renders as a plain
    nullable BLOB, which is inert and never read or written, instead of a
    `VECTOR(256)` that SQLite's dynamic typing would accept as a real column type
    and quietly let the tests pass on a schema no engine actually supports.
    """
    if "embedding" in embeddings.c:
        return
    from pgvector.sqlalchemy import Vector

    native = Vector(dim).with_variant(LargeBinary, "sqlite")
    embeddings.append_column(Column("embedding", native, nullable=True))


eval_labels = Table(
    "eval_labels",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "assignment_id",
        Integer,
        ForeignKey("assignments.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("note_id", Integer, ForeignKey("notes.id", ondelete="CASCADE"), nullable=False),
    Column("relevant", Integer, nullable=False),
    Column("rationale", Text, default=""),
    UniqueConstraint("assignment_id", "note_id", name="uq_eval_labels_pair"),
)


work_sessions = Table(
    "work_sessions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "assignment_id",
        Integer,
        ForeignKey("assignments.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("mode", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)


work_messages = Table(
    "work_messages",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "session_id",
        Integer,
        ForeignKey("work_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("role", String(32), nullable=False),
    Column("content", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)


sync_log = Table(
    "sync_log",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("ran_at", DateTime(timezone=True), nullable=False),
    Column("courses", Integer, nullable=False),
    Column("assignments", Integer, nullable=False),
    Column("detail", Text, default=""),
)


# Tables whose rows belong to exactly one user. `errors.assert_owned` checks
# membership here before trusting a caller-supplied id.
USER_OWNED_TABLES = {
    "courses": courses,
    "assignments": assignments,
    "notes": notes,
    "chunks": chunks,
    "eval_labels": eval_labels,
    "work_sessions": work_sessions,
}
