"""The database schema, defined once for both backends.

Day 1's schema lived in a hand-written `CREATE TABLE` string that only SQLite
understood. Hosting the app means Postgres, and maintaining two dialects of the
same DDL by hand is how the two silently drift apart.

So the schema moves into SQLAlchemy Core table definitions. One definition
emits correct DDL for both engines, the expression language builds queries that
are portable by construction, and Alembic can diff this metadata against a live
database to generate migrations.

This is Core, not the ORM: the app already has its own dataclasses in
`models.py` and does not need a second object-mapping layer. Core gives the
portability and the query builder without the identity map, lazy loading, and
session-lifecycle rules that come with the ORM.
"""

from __future__ import annotations

from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

# An explicit naming convention means Alembic generates stable, predictable
# names for constraints and indexes. Without it, autogenerated migrations churn
# on unnamed constraints and dropping one later becomes guesswork.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


users = Table(
    "users",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("apple_sub", String(255), unique=True),
    Column("email", String(320)),
    Column("display_name", String(255)),
    Column("created_at", DateTime(timezone=True), nullable=False),
)


courses = Table(
    "courses",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("canvas_id", String(64)),
    Column("name", Text, nullable=False),
    Column("course_code", String(64)),
    Column("synced_at", DateTime(timezone=True)),
    # Per-user uniqueness: two students can both be in Canvas course 101.
    UniqueConstraint("user_id", "canvas_id", name="uq_courses_user_canvas"),
)


assignments = Table(
    "assignments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("canvas_id", String(64)),
    Column(
        "course_id",
        Integer,
        ForeignKey("courses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("name", Text, nullable=False),
    Column("description", Text, default=""),
    Column("due_at", String(64)),
    Column("points_possible", Float),
    Column("submission_types", String(255), default=""),
    Column("html_url", Text),
    Column("synced_at", DateTime(timezone=True)),
    UniqueConstraint("course_id", "canvas_id", name="uq_assignments_course_canvas"),
)


notes = Table(
    "notes",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("course_id", Integer, ForeignKey("courses.id", ondelete="SET NULL")),
    Column("title", Text, nullable=False),
    Column("body", Text, nullable=False),
    Column("source_type", String(32), nullable=False, default="note"),
    Column("created_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("source_type IN ('note', 'transcript')", name="source_type"),
)


chunks = Table(
    "chunks",
    metadata,
    Column("id", Integer, primary_key=True),
    # Denormalised from notes: retrieval filters this table on every query.
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "note_id",
        Integer,
        ForeignKey("notes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("ordinal", Integer, nullable=False),
    Column("text", Text, nullable=False),
    Column("chunk_size", Integer, nullable=False),
    Column("chunk_overlap", Integer, nullable=False),
)


# `vector` stays a byte blob here so this definition mirrors the day-1 schema
# exactly. Commit 5 adds the native pgvector column alongside it.
embeddings = Table(
    "embeddings",
    metadata,
    Column("owner_type", String(32), primary_key=True),
    Column("owner_id", Integer, primary_key=True),
    Column("model", String(128), primary_key=True),
    Column("dim", Integer, nullable=False),
    Column("vector", LargeBinary, nullable=False),
)
Index("ix_embeddings_type_model", embeddings.c.owner_type, embeddings.c.model)


eval_labels = Table(
    "eval_labels",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "assignment_id",
        Integer,
        ForeignKey("assignments.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("note_id", Integer, ForeignKey("notes.id", ondelete="CASCADE"), nullable=False),
    Column("relevant", Integer, nullable=False),
    Column("rationale", Text, default=""),
    UniqueConstraint("assignment_id", "note_id", name="uq_eval_labels_pair"),
)


work_sessions = Table(
    "work_sessions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column(
        "assignment_id",
        Integer,
        ForeignKey("assignments.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("mode", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)


work_messages = Table(
    "work_messages",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "session_id",
        Integer,
        ForeignKey("work_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    ),
    Column("role", String(32), nullable=False),
    Column("content", Text, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)


sync_log = Table(
    "sync_log",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True),
    Column("ran_at", DateTime(timezone=True), nullable=False),
    Column("courses", Integer, nullable=False),
    Column("assignments", Integer, nullable=False),
    Column("detail", Text, default=""),
)


# Tables whose rows belong to exactly one user. `errors.assert_owned` checks
# membership here before trusting a caller-supplied id.
USER_OWNED_TABLES = {
    "courses": courses,
    "assignments": assignments,
    "notes": notes,
    "chunks": chunks,
    "eval_labels": eval_labels,
    "work_sessions": work_sessions,
}
