import { useState } from "react";
import "./landing.css";

type AuthMode = "login" | "signup";
function Mark({ small = false }: { small?: boolean }) {
  return <span className={`lp-mark${small ? " lp-mark-small" : ""}`} aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><path d="M16 7v18M7 11l18 10M7 21l18-10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="m12 3 4 4 4-4M12 29l4-4 4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></span>;
}
function Arrow() { return <span aria-hidden="true">↗</span>; }
function Icon({ name }: { name: "folder" | "cards" | "test" | "spark" | "search" }) {
  return <svg className="lp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name === "folder" ? <path d="M3 7V5h6l2 2h10v12H3V7Z"/> : name === "cards" ? <><rect x="7" y="6" width="13" height="15" rx="2"/><path d="M16 3H5a2 2 0 0 0-2 2v12M11 11h5m-5 4h3"/></> : name === "test" ? <><rect x="5" y="3" width="14" height="18" rx="2"/><path d="m8 9 1 1 2-2m2 1h3m-8 6 1 1 2-2m2 1h3"/></> : name === "search" ? <><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></> : <path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>}</svg>;
}

export function LandingPage({ onAuthenticate }: { onAuthenticate: (mode: AuthMode) => void }) {
  const [flipped, setFlipped] = useState(false);
  const [preview, setPreview] = useState<"notes" | "flashcards">("notes");
  const signup = () => onAuthenticate("signup");
  return <div className="landing" id="top">
    <a className="lp-skip" href="#main-content">Skip to content</a>
    <header className="lp-header lp-container">
      <a href="#top" className="lp-brand" aria-label="Moot home"><Mark />moot<span className="lp-brand-period">.</span></a>
      <nav className="lp-nav" aria-label="Main navigation"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#ask-moot">Ask Moot <span className="lp-tiny-spark">✧</span></a></nav>
      <div className="lp-header-actions"><button className="lp-login" onClick={() => onAuthenticate("login")}>Log in</button><button className="lp-button lp-button-small" onClick={signup}>Get started <Arrow /></button></div>
    </header>
    <main id="main-content">
      <section className="lp-hero lp-container" aria-labelledby="hero-title">
        <div className="lp-eyebrow"><span className="lp-status-dot"/> A little clarity. A lot of possibility.</div>
        <h1 id="hero-title">Less overwhelm.<br/><em>More understanding.</em></h1>
        <p className="lp-hero-description">Turn your notes into knowledge that stays.<br/>One thoughtful space to organize, practice, and find your aha.</p>
        <div className="lp-hero-actions"><button className="lp-button" onClick={signup}>Start studying <Arrow /></button><a className="lp-button lp-button-secondary" href="#preview">Explore Moot <span aria-hidden="true">↓</span></a></div>
        <p className="lp-hero-footnote">Your notes. Your pace. Your space.</p>
        <div className="lp-preview-wrap" id="preview">
          <div className="lp-preview-topline"><span><span className="lp-status-dot"/> A calmer kind of study session</span><span>ILLUSTRATIVE PREVIEW</span></div>
          <div className="lp-app-preview">
            <aside className="lp-preview-sidebar" aria-label="Example workspace sidebar"><div className="lp-preview-brand"><Mark small/> moot.</div><div className="lp-workspace-label">MY WORKSPACE</div><div className="lp-sidebar-item"><span>⌂</span> Overview</div><div className="lp-sidebar-item lp-sidebar-selected"><Icon name="folder"/> My notes <span className="lp-count">12</span></div><div className="lp-sidebar-item lp-nested"><span className="lp-folder-dot"/> Biology</div><div className="lp-sidebar-item lp-nested"><span className="lp-folder-dot lp-dot-clay"/> Psychology</div><div className="lp-sidebar-item lp-nested"><span className="lp-folder-dot lp-dot-lilac"/> Literature</div><div className="lp-workspace-label lp-sidebar-gap">STUDY SPACE</div><div className="lp-sidebar-item"><Icon name="cards"/> Flashcards</div><div className="lp-sidebar-item"><Icon name="test"/> Practice tests</div><div className="lp-sidebar-item"><Icon name="search"/> Find a deck</div><div className="lp-sidebar-bottom"><span className="lp-avatar">J</span><span>Your workspace<small>A little better, every day.</small></span></div></aside>
            <div className="lp-preview-main"><div className="lp-breadcrumb">My notes <span>/</span> Biology <span className="lp-private">♧ Private</span></div><div className="lp-preview-heading"><div><p className="lp-kicker">LET'S MAKE IT CLICK</p><h2>A world worth understanding.</h2><p>Big ideas. Small steps. You've got this.</p></div><span className="lp-orbit" aria-hidden="true">✳</span></div>
              <div className="lp-preview-tabs" aria-label="Example content"><button className={preview === "notes" ? "lp-tab-active" : ""} aria-pressed={preview === "notes"} onClick={() => setPreview("notes")}>Your notes <span>3</span></button><button className={preview === "flashcards" ? "lp-tab-active" : ""} aria-pressed={preview === "flashcards"} onClick={() => setPreview("flashcards")}>Flashcards <span>1</span></button><span className="lp-tab-detail">BIOLOGY · CHAPTER 04</span></div>
              {preview === "notes" ? <div className="lp-note-grid"><article className="lp-note lp-note-featured"><span className="lp-note-symbol">⌘</span><span className="lp-note-tag">CELL BIOLOGY</span><h3>The little things<br/>that make life.</h3><p>Cell structure, organelles, and the extraordinary world within.</p><div className="lp-note-bottom"><span>Cell structure</span><span>↗</span></div></article><div className="lp-note-stack"><article className="lp-note"><span className="lp-note-tag">CHAPTER 04</span><h3>Energy, in motion.</h3><p>Photosynthesis & cellular respiration</p><span className="lp-note-date">Edited just now</span></article><article className="lp-note"><span className="lp-note-tag">THE BIG PICTURE</span><h3>Connected by nature.</h3><p>Ecosystems & food webs</p><span className="lp-note-date">Edited yesterday</span></article></div></div> : <button className="lp-demo-flashcard" onClick={() => setFlipped(!flipped)} aria-label={flipped ? "Mitochondria convert energy from food into ATP, which powers cellular processes. Show flashcard question." : "Why are mitochondria called the powerhouse of the cell? Reveal flashcard answer."}><span className="lp-note-tag">CELL BIOLOGY · {flipped ? "ANSWER" : "QUESTION"}</span><strong>{flipped ? "Mitochondria convert energy from food into ATP, which powers cellular processes." : "Why are mitochondria called the powerhouse of the cell?"}</strong><span>↻ {flipped ? "Back to question" : "Tap to reveal"}</span></button>}
              <div className="lp-study-strip"><span className="lp-strip-icon"><Icon name="cards"/></span><div><strong>A little practice goes a long way.</strong><p>Bring your notes to life with flashcards.</p></div><button onClick={() => { setPreview("flashcards"); setFlipped(false); }}>Try a card <span aria-hidden="true">→</span></button></div>
            </div>
            <aside className="lp-preview-chat"><div className="lp-chat-title"><Mark small/><strong>Ask Moot</strong><span>✧</span></div><div className="lp-chat-context"><span className="lp-status-dot"/> Grounded in your notes</div><div className="lp-chat-question">How do plant cells turn sunlight into energy?</div><div className="lp-chat-answer"><Mark small/><p>Think of chloroplasts as tiny solar panels. They capture light and use it to turn water and carbon dioxide into glucose.</p><p>That glucose stores energy the plant can use to grow. <span className="lp-citation">1</span></p><div className="lp-source"><Icon name="folder"/><span>Energy, in motion.<small>From your Biology folder</small></span></div></div><div className="lp-chat-placeholder">Aha. That makes sense.<span>↗</span></div></aside>
          </div>
        </div>
        <div className="lp-under-preview"><span>MADE FOR THE WAY YOU LEARN</span><p>A clearer mind. A more connected study routine.</p><div><span>✧ Thoughtfully simple</span><span>♧ Private by default</span><span>↗ Built around your notes</span></div></div>
      </section>
      <section className="lp-section lp-container" id="features" aria-labelledby="features-title"><div className="lp-section-heading"><div><p className="lp-kicker">LESS FRICTION. MORE FOCUS.</p><h2 id="features-title">Everything you need.<br/><em>Room to breathe.</em></h2></div><p>From your first messy note to your next big exam.<br/>Your study essentials, finally in one place.</p></div>
        <div className="lp-feature-grid"><article className="lp-feature lp-feature-flashcards"><div className="lp-feature-icon"><Icon name="cards"/></div><h3>Make it stick.</h3><p>Turn your notes into flashcards. Build understanding,<br className="lp-desktop-break"/> one small moment of recall at a time.</p><div className="lp-card-art"><div className="lp-card-back"/><button className="lp-flip-card" onClick={() => setFlipped(!flipped)} aria-label={flipped ? "The mitochondrion. Show example flashcard question." : "Which organelle powers the cell? Reveal example flashcard answer."}><span>BIOLOGY <span>01 / 01</span></span><strong>{flipped ? "The mitochondrion." : "Which organelle powers the cell?"}</strong><small>↻ {flipped ? "Show question" : "Click to reveal"} · Example card</small></button></div></article>
          <article className="lp-feature lp-feature-folders"><div className="lp-feature-icon"><Icon name="folder"/></div><h3>A place for every thought.</h3><p>Keep notes and folders beautifully organized.<br/>Pick up exactly where your curiosity left off.</p><div className="lp-folder-art"><div><span className="lp-folder-dot"/> Biology <span>04 notes</span></div><div><span className="lp-folder-dot lp-dot-clay"/> Psychology <span>05 notes</span></div><div><span className="lp-folder-dot lp-dot-lilac"/> Literature <span>03 notes</span></div></div></article>
          <article className="lp-feature lp-feature-compact"><div className="lp-feature-icon"><Icon name="test"/></div><h3>Meet your next exam.</h3><p>Generate practice tests from your flashcard decks. Find what clicks and what needs another look.</p><div className="lp-small-art"><span className="lp-check">✓</span><span>Understanding, over memorizing.</span></div></article>
          <article className="lp-feature lp-feature-compact"><div className="lp-feature-icon"><Icon name="spark"/></div><h3>Connect the dots.</h3><p>Match your notes to topics so scattered ideas become a clearer picture.</p><div className="lp-topic-art"><span>Your notes</span><i>⤳</i><span>The bigger picture</span></div></article>
          <article className="lp-feature lp-feature-compact"><div className="lp-feature-icon"><Icon name="search"/></div><h3>Find a fresh perspective.</h3><p>Discover shared decks and explore a different way into the subjects you're studying.</p><div className="lp-deck-tags"><span>Biology</span><span>History</span><span>+ more</span></div></article></div>
      </section>
      <section className="lp-section lp-container lp-how" id="how-it-works" aria-labelledby="how-title"><p className="lp-kicker">A SMALL START. A REAL DIFFERENCE.</p><h2 id="how-title">Find your flow.</h2><div className="lp-steps">{[{ title: "Bring your thoughts.", text: "Add your notes and give them a home. A lecture, a chapter, a question — start anywhere." }, { title: "Make them your own.", text: "Create flashcards, connect topics, or ask Moot to help you untangle a tricky idea." }, { title: "Let understanding grow.", text: "Practice at your pace. Test what you know. Come back with a little more confidence." }].map((step, i) => <article key={step.title}><span className="lp-step-number">0{i + 1}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
      <section className="lp-container" id="ask-moot" aria-labelledby="ask-title"><div className="lp-ask"><div className="lp-ask-copy"><p className="lp-kicker"><Mark small/> MEET ASK MOOT</p><h2 id="ask-title">A little help.<br/><em>A bigger aha.</em></h2><p>Some ideas just need a different explanation.<br/>Ask Moot answers from your own notes, helping you make sense of what you're learning.</p><div className="lp-ask-points"><span>↳ Rooted in your study material</span><span>↳ Sources you can come back to</span><span>↳ Your notes stay private by default</span></div><button className="lp-text-button" onClick={signup}>Meet your study companion <span aria-hidden="true">↗</span></button></div><div className="lp-ask-demo"><div className="lp-example-label">AN EXAMPLE CONVERSATION</div><div className="lp-ask-question">Can you explain active recall simply?</div><div className="lp-ask-response"><Mark/><div><p>It's giving your brain a chance to find the answer before you look it up.</p><p>Instead of rereading a page, close your notes and ask yourself: <em>what do I remember?</em> That effort helps strengthen the memory. <span className="lp-citation">1</span></p><div className="lp-source"><Icon name="folder"/><span>Learning & memory<small>Psychology · Your notes</small></span></div></div></div><div className="lp-ask-demo-bottom"><span className="lp-status-dot"/> Your material. A clearer explanation.</div></div></div></section>
      <section className="lp-final lp-container"><Mark/><p className="lp-kicker">A LITTLE LESS CHAOS. A LITTLE MORE CLARITY.</p><h2>Good things start<br/><em>with a clearer mind.</em></h2><p>Make room for the way you learn.</p><button className="lp-button" onClick={signup}>Find your focus with Moot <Arrow/></button></section>
    </main>
    <footer className="lp-footer lp-container"><div><a className="lp-brand" href="#top"><Mark/>moot.</a><p>A thoughtful space for curious minds.</p></div><nav aria-label="Footer navigation"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#ask-moot">Ask Moot</a><button onClick={() => onAuthenticate("login")}>Log in <Arrow/></button></nav><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Moot</span><span>Made for your next aha. <span aria-hidden="true">✧</span></span></div></footer>
  </div>;
}
